---
- name: This is a backup
  hosts: migration
  user: pascaline
  become: yes
  gather-facts: yes
  connection: local 
  tasks:
    - shell: mysqldump -h localhost -uroot -pg@17m8VK9Dbh26 migrationutility > migrationutility.sql
    - fetch:
       src: /var/lib/awx/projects/migrationutility.sql
       dest: /var/lib/awx/projects/
       flat: true
