- hosts: pascaline
- user: pascaline
  become: true
  connection: local 
  gather-facts: yes
  tasks:
    - shell: mysqldump -h localhost -uroot -pg@17m8VK9Dbh26 migrationutility > migrationutility.sql
    - fetch:
       src: /var/lib/awx/projects/migrationutility.sql
       dest: /var/lib/awx/projects/
       flat: true
