- hosts: localhost
  connection: local
  become_user: root
  become: true
  tasks:
    - shell: mysqlpump -h localhost -uroot -pg@17m8VK9Dbh26 migrationutility > migrationutility.sql
    - fetch:
       src: /var/lib/awx/projects/migrationutility.sql
       dest: /var/lib/awx/projects/
       flat: true
